#!/bin/bash
## Mystcraft settings ##
sed -i -e 's/B:options.crafting.enableAgebook=true/B:options.crafting.enableAgebook=false/' $SERVER_ROOT/config/mystcraft_config.txt
sed -i -e 's/B:options.crafting.enableLinkModifier=true/B:options.crafting.enableLinkModifier=false/' $SERVER_ROOT/config/mystcraft_config.txt
sed -i -e 's/B:options.crafting.enableLinkbook=true/B:options.crafting.enableLinkbook=false/' $SERVER_ROOT/config/mystcraft_config.txt
sed -i -e 's/B:options.crafting.enableNotebook=true/B:options.crafting.enableNotebook=false/' $SERVER_ROOT/config/mystcraft_config.txt
sed -i -e 's/B:denseores.enabled=true/B:denseores.enabled=false/' $SERVER_ROOT/config/mystcraft_config.txt
sed -i -e 's/B:options.renderlabels=false/B:options.renderlabels=true/' $SERVER_ROOT/config/mystcraft_config.txt

## Computercraft Settings ##
sed -i -e 's/B:enableAPI_http=false/B:enableAPI_http=true/' $SERVER_ROOT/config/ComputerCraft.cfg

## NetherStuffs
sed -i -e 's/B:OverrideChunkClass=true/B:OverrideChunkClass=false/' $SERVER_ROOT/config/NetherStuffs.cfg # Make it so the bukkitChunk error doesnt appear.

## Recipe Remover ##
grep 'removedIDs=9080' $SERVER_ROOT/config/RecipeRemover.cfg 2>&1 > /dev/null
if [ $? -eq 1 ]; then
	sed -i -e 's/}/    S:removedIDs=9080\n}/' $SERVER_ROOT/config/RecipeRemover.cfg
fi
grep 'removedIDs=13127' $SERVER_ROOT/config/RecipeRemover.cfg 2>&1 > /dev/null
if [ $? -eq 1 ]; then
	sed -i -e 's/}/    S:removedIDs=13127\n}/' $SERVER_ROOT/config/RecipeRemover.cfg
fi
grep 'removedIDs=11458' $SERVER_ROOT/config/RecipeRemover.cfg 2>&1 > /dev/null
if [ $? -eq 1 ]; then
	sed -i -e 's/}/    S:removedIDs=11458\n}/' $SERVER_ROOT/config/RecipeRemover.cfg
fi

## NEI Server settings ##
sed -i -e 's/delete=OP/delete=ALL/' $SERVER_ROOT/config/NEIServer.cfg

## ForgeChunkLoader ##
sed -i -e 's/I:maximumTicketCount=200/I:maximumTicketCount=65535/g' $SERVER_ROOT/config/forgeChunkLoading.cfg
sed -i -e 's/I:maximumChunksPerTicket=25/I:maximumChunksPerTicket=200/g' $SERVER_ROOT/config/forgeChunkLoading.cfg
sed -i -e 's/I:playerTicketCount=500/I:playerTicketCount=500/g' $SERVER_ROOT/config/forgeChunkLoading.cfg

## Elemental Tinkerer ##
sed -i -e 's/B:elementiumOre.safe=false/B:elementiumOre.safe=true/g' $SERVER_ROOT/config/ElementalTinkerer.cfg

## NEI ##
sed -i -e 's/mistaqur.checkUpdate=true/mistaqur.checkUpdate=false/g' $SERVER_ROOT/config/NEI.cfg

## Thaumic Bees ##
sed -i -e 's/B:disableVersionCheck=false/B:disableVersionCheck=true/g' $SERVER_ROOT/config/ThaumicBees.cfg

## CoFH Core ##
sed -i -e 's/B:EnableUpdateNotifications=true/B:EnableUpdateNotifications=false/g' $SERVER_ROOT/config/cofh/CoFHCore.cfg

## Thermal Expansion ##
sed -i -e 's/B:EnableUpdateNotifications=true/B:EnableUpdateNotifications=false/g' $SERVER_ROOT/config/cofh/ThermalExpansion.cfg

## Eplus ##
sed -i -e 's/B:AllowUpdateCheck=true/B:AllowUpdateCheck=false/g' $SERVER_ROOT/config/eplus.cfg

## Forrestry ##
sed -i -e 's/tweaks.upgradenotice.disabled=false/tweaks.upgradenotice.disabled=true/g' $SERVER_ROOT/config/forestry/common.conf

## Applied Energistics ##
sed -i -e 's/B:enableVersionChecker=true/B:enableVersionChecker=false/g' $SERVER_ROOT/config/AppliedEnergistics.cfg

## RailCraft ##
sed -i -e 's/B:check.version.online=true/B:check.version.online=false/g' $SERVER_ROOT/config/railcraft/railcraft.cfg
