#!/bin/bash
MINE_CONFIG=~/serverconfig.cfg
if [ -f $MINE_CONFIG ]; then
    source $MINE_CONFIG
else
    echo "Config file: '$MINE_CONFIG' does not exist"
    exit
fi

# check files and folders exist in mods folder (or else it will delete *everything* in the folder
if [ `find $UPDATE_DIR/mods | wc -l` -gt 1 ]; then
    rsync -avz --delete-after --exclude=disabled --exclude=.git --exclude=.gitignore $UPDATE_DIR/mods/ $SERVER_ROOT/mods/
else
    echo "Mods update folder is empty"
    echo "Aborting update"
    exit
fi

# check files and folders exist in coremods folder (or else it will delete *everything* in the folder
if [ `find $UPDATE_DIR/coremods | wc -l` -gt 1 ]; then
    rsync -avz --delete-after  --exclude=.git --exclude=disabled $UPDATE_DIR/coremods/ $SERVER_ROOT/coremods/ 
else
    echo "Config update folder is empty"
    echo "Aborting update"
    exit
fi

# check files and folders exist in config folder (or else it will delete *everything* in the folder
if [ `find $UPDATE_DIR/config | wc -l` -gt 1 ]; then
    rsync -avz --delete-after --exclude=.git $UPDATE_DIR/config/ $SERVER_ROOT/config/
else
    echo "Config update folder is empty"
    echo "Aborting update"
    exit
fi

# Remove excluded mods
find $SERVER_ROOT/mods/ -iname '*VanityBlocks*' -exec rm {} \;

cp $UPDATE_DIR/minecraft_server.jar $SERVER_ROOT/minecraft_server.jar
$SERVER_ROOT/bin/adjustconf
